/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.User;
import Control.ConfigDB;
import Control.DB;
import Control.UsersControl;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class Desktop extends javax.swing.JFrame {

    public static DB db = new DB();
    public static UsersControl userscontrol = new UsersControl();
    public static User currentUser;

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        if (!db.connect(new ConfigDB().getConfig())) {
            ViewConfigDB frm = new ViewConfigDB(this, true);
            frm.setVisible(true);
            db.connect(new ConfigDB().getConfig());
        }

        ViewLogin vl = new ViewLogin(this, true);
        vl.setVisible(true);

        if (this.currentUser != null) {
            initComponents();
            this.setLocationRelativeTo(null);
        } else {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblUsers = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblConfig = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        lbltextSalary = new javax.swing.JLabel();
        lblVehicules = new javax.swing.JLabel();
        lbltextVehicules = new javax.swing.JLabel();
        lblappointment = new javax.swing.JLabel();
        lbltextVehicules1 = new javax.swing.JLabel();
        lblRevisions = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users.png"))); // NOI18N
        lblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsersMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Users");

        lblConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/config.png"))); // NOI18N
        lblConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblConfigMousePressed(evt);
            }
        });

        lblSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary.png"))); // NOI18N
        lblSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalaryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSalaryMousePressed(evt);
            }
        });

        lbltextSalary.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lbltextSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltextSalary.setText("Salary ");

        lblVehicules.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/car1.png"))); // NOI18N
        lblVehicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVehiculesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVehiculesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVehiculesMousePressed(evt);
            }
        });

        lbltextVehicules.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lbltextVehicules.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltextVehicules.setText("Vehicules");

        lblappointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblappointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar1.png"))); // NOI18N
        lblappointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblappointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblappointmentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblappointmentMousePressed(evt);
            }
        });

        lbltextVehicules1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lbltextVehicules1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltextVehicules1.setText("Appointments");

        lblRevisions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-list.png"))); // NOI18N
        lblRevisions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRevisionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRevisionsMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblRevisionsMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel3.setText("Revisions");

        jDesktopPane1.setLayer(lblUsers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblConfig, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblSalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbltextSalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblVehicules, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbltextVehicules, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblappointment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbltextVehicules1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblRevisions, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbltextSalary))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(lblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbltextVehicules)
                        .addGap(45, 45, 45)
                        .addComponent(lbltextVehicules1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblVehicules, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(lblappointment, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRevisions, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(306, 306, 306))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRevisions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblVehicules, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUsers, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSalary, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblappointment, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltextVehicules, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(lbltextSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lbltextVehicules1)
                    .addComponent(jLabel3))
                .addGap(500, 500, 500))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMousePressed
   
            ViewUsers vw = new ViewUsers();
            vw.setVisible(true);
        
    }//GEN-LAST:event_lblUsersMousePressed

    private void lblUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseEntered
        lblUsers.setIcon(new ImageIcon(getClass().getResource("/images/users2.png")));
    }//GEN-LAST:event_lblUsersMouseEntered

    private void lblUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseExited
        lblUsers.setIcon(new ImageIcon(getClass().getResource("/images/users.png")));
    }//GEN-LAST:event_lblUsersMouseExited

    private void lblConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigMouseEntered
        lblConfig.setIcon(new ImageIcon(getClass().getResource("/images/config2.png")));
    }//GEN-LAST:event_lblConfigMouseEntered

    private void lblConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigMouseExited
        lblConfig.setIcon(new ImageIcon(getClass().getResource("/images/config.png")));
    }//GEN-LAST:event_lblConfigMouseExited

    private void lblConfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfigMousePressed
        ViewConfigDB frm = new ViewConfigDB(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_lblConfigMousePressed

    private void lblSalaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalaryMouseEntered
        lblSalary.setIcon(new ImageIcon(getClass().getResource("/images/salary2.png")));
    }//GEN-LAST:event_lblSalaryMouseEntered

    private void lblSalaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalaryMouseExited
        lblSalary.setIcon(new ImageIcon(getClass().getResource("/images/salary.png")));
    }//GEN-LAST:event_lblSalaryMouseExited

    private void lblSalaryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalaryMousePressed
        ViewSalary vs = new ViewSalary();
        vs.setVisible(true);
    }//GEN-LAST:event_lblSalaryMousePressed

    private void lblVehiculesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVehiculesMouseEntered
        lblVehicules.setIcon(new ImageIcon(getClass().getResource("/images/car2.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_lblVehiculesMouseEntered

    private void lblVehiculesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVehiculesMouseExited
        lblVehicules.setIcon(new ImageIcon(getClass().getResource("/images/car1.png")));
    }//GEN-LAST:event_lblVehiculesMouseExited

    private void lblVehiculesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVehiculesMousePressed
        ViewVehicules vw = new ViewVehicules();
        vw.setVisible(true);
    }//GEN-LAST:event_lblVehiculesMousePressed

    private void lblappointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblappointmentMouseEntered
        lblappointment.setIcon(new ImageIcon(getClass().getResource("/images/calendar2.png")));
    }//GEN-LAST:event_lblappointmentMouseEntered

    private void lblappointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblappointmentMouseExited
        lblappointment.setIcon(new ImageIcon(getClass().getResource("/images/calendar1.png")));
    }//GEN-LAST:event_lblappointmentMouseExited

    private void lblappointmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblappointmentMousePressed
        ViewAppointments1 vw = new ViewAppointments1();
        jDesktopPane1.add(vw);
        vw.setVisible(true);
    }//GEN-LAST:event_lblappointmentMousePressed

    private void lblRevisionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRevisionsMouseEntered
        lblRevisions.setIcon(new ImageIcon(getClass().getResource("/images/shopping-list2.png")));
    }//GEN-LAST:event_lblRevisionsMouseEntered

    private void lblRevisionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRevisionsMouseExited
        lblRevisions.setIcon(new ImageIcon(getClass().getResource("/images/shopping-list.png")));
    }//GEN-LAST:event_lblRevisionsMouseExited

    private void lblRevisionsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRevisionsMouseReleased
        ViewRevisions va  = new ViewRevisions();
        va.setVisible(true);
    }//GEN-LAST:event_lblRevisionsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblRevisions;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblVehicules;
    private javax.swing.JLabel lblappointment;
    private javax.swing.JLabel lbltextSalary;
    private javax.swing.JLabel lbltextVehicules;
    private javax.swing.JLabel lbltextVehicules1;
    // End of variables declaration//GEN-END:variables
}
